export const uniqueTags = [
  'AI',
  'Accessibility',
  'Adulting',
  'Analogy',
  'Balance Advantage Funds',
  'Balanced Investing',
  'Beginner Investing',
  'Behavioral Biases',
  'Behavioral Finance',
  'Bias',
  'Bond Market',
  'Budgeting',
  'Business',
  'Capital Appreciation',
  'Cognitive Biases',
  'Comparison',
  'Compounding',
  'Couples',
  'Cricket',
  'Debt Funds',
  'Demat Account',
  'Diversification',
  'Early Investment',
  'Economic Slowdown',
  'Entrepreneurs',
  'Entrepreneurship',
  'Equity',
  'FAQ',
  'FEMA',
  'FOMO Investing',
  'Family Floater',
  'Financial Advisor',
  'Financial Freedom',
  'Financial Goals',
  'Financial Literacy',
  'Financial Planning',
  'Financial Psychology',
  'Financial Security',
  'Financial Services',
  'Fintech',
  'Goal-Based Investing',
  'Graduates',
  'Health Insurance',
  'Healthcare',
  'Healthcare Costs',
  'High Returns',
  'Hybrid Funds',
  'Impulse Investing',
  'Income',
  'India Investment',
  'Individual Plan',
  'Inflation',
  'Investing',
  'Investing Analogy',
  'Investing Basics',
  'Investing Mistakes',
  'Investing Strategies',
  'Investing Strategy',
  'Investment Advice',
  'Investment Discipline',
  'Investment Strategy',
  'Investments',
  'Lifestyle',
  'Lifestyle Inflation',
  'Liquidity',
  'Long-Term Investing',
  'Lumpsum',
  'Market Cap',
  'Market Timing',
  'Market Volatility',
  'Middle Class',
  'Millennials',
  'Mindset',
  'Monopoly',
  'Mutual Funds',
  'Myths',
  'NRI Investing',
  'PMS',
  'Panic Selling',
  'Portfolio Management',
  'Post-Pandemic',
  'Retirement',
  'Retirement Planning',
  'Risk Management',
  'Risk Mitigation',
  'Risk Tolerance',
  'Robo-Advisors',
  'Rupee Cost Averaging',
  'SIP',
  'STP',
  'Saving',
  'Savings',
  'Short-Term Investment',
  'Side Hustle',
  'Taxation',
  'Top-up SIP',
  'Wealth Building',
  'Wealth Creation',
  'Wealth Management',
] as const;

export type ArticleTag = (typeof uniqueTags)[number];

// console.log(
//   blogs.map((blog) =>
//     blog.categories.reduce((acc, category) => {
//       acc.add(category);
//       return acc;
//     }, new Set<string>())
//   )
// );

// sorted unique categories
// export const uniqueCategories = Array.from(
//   blogs.reduce((acc, blog) => {
//     blog.categories.forEach((category) => acc.add(category));
//     return acc;
//   }, new Set<string>())
// ).sort();
