import Footer from '@/components/shared/footer';
import Navbar from '@/components/shared/navbar';
import TopNav from '@/components/shared/top-nav';
import '@/styles/style.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Finatex',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} bg-black overflow-x-hidden`}>
        <header id='header' className={'style-six'}>
          <TopNav />
          <Navbar />
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
